config/routes.rb
Rails.application.routes.draw do
  resources :works do
    member do
      put "like", to: "works#upvote"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'posts#index'
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end
  get '/about', to: 'pages#about'

  resources "contacts", only: [:new, :create]

end

app/models/work.rb
class Work < ActiveRecord::Base
	acts_as_votable
	default_scope { order('created_at DESC') }
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	belongs_to :user
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy, :upvote]
  load_and_authorize_resource

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = current_user.works.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @work.upvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :description, :image)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= simple_form_for(@work) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control'} %>
    <%= f.input :description, input_html: { class: 'form-control'} %>
    <%= f.input :image_file_name, input_html: { class: 'form-control'} %>
    <%= f.input :image_content_type, input_html: { class: 'form-control'} %>
    <%= f.input :image_file_size, input_html: { class: 'form-control'} %>
    <%= f.input :image_updated_at, input_html: { class: 'form-control'} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, input_html: { class: 'btn btn-success'} %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<% @works.each do |work| %>
    <!-- Main Content -->
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="work-preview">
                        <h2 class="work-title">
                            <h1 align="center"><%= link_to  "#{work.title}", work %></h1>
                        </h2>
                        <div align="center">
                            <%= image_tag work.image.url(:medium) %>
                        </div>
                        <a>
                        <h3 class="work-subtitle">
                            <%= raw(work.description) %>
                        </h3>
                      </a>
                    <p class="post-meta">Posted by <a href="#"><%= work.user.email %></a> on <%= work.created_at %></p>
                </div>
                <hr>
            </div>
        </div>

    <hr>
<% end %>

app/views/works/index.html.haml
#works.transitions-enabled
    - @works.each do |work|
        .box.panel.panel-default
            = link_to (image_tag work.image.url), work
            %h2= link_to work.title, work
            %p.user
                Submitted by
                = work.user.email
                on
                = work.created_at

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work.description %>
</p>

<p>
  <strong>Image file name:</strong>
  <%= @work.image_file_name %>
</p>

<p>
  <strong>Image content type:</strong>
  <%= @work.image_content_type %>
</p>

<p>
  <strong>Image file size:</strong>
  <%= @work.image_file_size %>
</p>

<p>
  <strong>Image updated at:</strong>
  <%= @work.image_updated_at %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>

app/views/works/show.html.haml
#work_show.row
  .col-md-8-col-md-offset-2
    .panel.panel-default
      .panel-heading.work_image
        = image_tag @work.image.url
      .panel-body
        %h1= @work.title
        %p.description= raw(@work.description)
        .panel-footer
          .row
            .col-md-6
              %p.user
                Submitted by
                = @work.user.email
                on
                = @work.created_at
            .col-md-6
              .btn-group.pull-right
                = link_to like_work_path(@work), method: :put, class: "btn btn-success" do
                  %span.glyphicon.glyphicon-thumbs-up
                    = @work.get_upvotes.size
                = link_to "Voltar", works_path, class: "btn btn-primary"