config/routes.rb
Rails.application.routes.draw do
  resources :works do
    member do
      put "like", to: "works#upvote"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'posts#index'
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end
  get '/about', to: 'pages#about'

  resources "contacts", only: [:new, :create]

end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	default_scope { order('created_at DESC') }
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates_presence_of [:title,:body]
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote] 
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- Main Content -->
<div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <% @posts.each do |post| %>
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color: #3399ff;">
                    <h4>
                        <%= link_to  "#{post.title}", post %>
                    </h4>
                </div>
                <div class="panel-body" align="center" style="background-color: #ffeead;">
                    <h3>
                        <%= raw(post.body.split[0..100].join(" ")) %>...
                    </h3>
                </div>
                <div class="panel-footer" style="background-color: #ffc700;">
                    <strong>Por <%= image_tag post.user.gravatar_url %> <%= post.user.email %> a <%= time_ago_in_words(post.created_at) %> atras.</strong>
                </div>
            </div>
            <hr>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    	<div class="panel panel-default">
    		<div class="panel-heading" style="background-color: #3399ff;">
				<p>
  					<h1 align="center"><%= @post.title %></h1>
				</p>
			</div>
			<div class="panel-body" style="background-color: #ffeead;">

				<p>
  					<strong><%= raw(@post.body) %></strong>
				</p>
				<div class="btn-group pull-right">
                	<%= link_to like_post_path(@post), method: :put, class: "btn btn-success" do %>
                  		<span class="glyphicon glyphicon-thumbs-up"/>
                    		<%= @post.get_upvotes.size %>
                	<% end %>
                	<%= link_to 'Voltar', posts_path, class: "btn btn-warning" %>
                </div>
			</div>
			<div class="panel-footer" style="background-color: #ffc700">
				<strong>Por <%= image_tag @post.user.gravatar_url %> <%= @post.user.email %> a <%= time_ago_in_words(@post.created_at) %> atras.</strong>
			</div>
  		</div>
  		<div class="panel panel-default">
  			<div class="panel-heading" style="background-color: #3399ff">
				<h2><%= @post.comments.count %> comentarios</h2>
			</div>
  			<div class="panel-body" style="background-color: #ffeead">
  				<%= render @post.comments %>
				<h3>Add a comment:</h3>
				<%= render "comments/form" %>
			</div>
  		</div>
  	</div>
</div>