config/routes.rb
Rails.application.routes.draw do
  resources :works do
    member do
      put "like", to: "works#upvote"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'posts#index'
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
    resources :comments
  end
  get '/about', to: 'pages#about'

  resources "contacts", only: [:new, :create]

end

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <footer class="foot">
        <div class="container" id="foot">
            <div class="container">
                <div class="footer-col col-md-4">
                    <h3>Me ligue!</h3>
                    <strong><p>Oi:(48)84669228</br>
                    Tim:(48)96558242</br>
                    Fixo:(48)36470292</br>
                    Skype: josemariamicoli<p>
                </div>
                <div class="footer-col col-md-4">
                    <h3 align="center">Me encontre na web!</h3>
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/JMMicoli">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://facebook.com/josemaria.micoli">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/JoseMariaMicoli">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.google.com/+JoseMicoliMicoli">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-google-plus fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/c/JoseMicoliMicoli">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="http://stackoverflow.com/users/2762643/jose-maria-micoli">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-stack-overflow fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Freelancer</h3>
                    <p>Esta precissando de um desenvolvedor web de forma freelancer entre em <a href="/contacts/new">contato</a>, estou aberto a novos trabalhos.</p>
                </div>
            </div>
        </div>
    </footer>

    <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; micoli.net.br 2015 Jose Maria Micoli todos os direitos reservados.
                    </div>
                </div>
            </div>
    </div>

app/views/layouts/_header.html.erb
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Jose Maria Micoli">

    <title>Micoli's Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.haml
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

%title>Micoli's Blog

<!-- Bootstrap Core CSS -->
%link{:rel => :stylesheet, :type => :"text/css", :href => "/css/bootstrap.css"}


<!-- Custom CSS -->
%link{:rel => :stylesheet, :type => :"text/css", :href => "/css/my-clean-blog.css"}


<!-- Custom Fonts -->
%link{:rel => :stylesheet, :type => :"text/css", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"}
%link{:rel => :stylesheet, :type => :"text/css", :href => "http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"}
%link{:rel => :stylesheet, :type => :"text/css", :href => "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"}

= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags

app/views/layouts/_maincontent.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: 'btn btn-success' %>


<%= image_tag @post.image.url %>
<%= image_tag @post.image.url(:medium) %>
<%= image_tag @post.image.url(:thumb) %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Micoli's Blog</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="glyphicon glyphicon-home" href="/">Home</a>
                    </li>
                    <li>
                        <%= link_to "Sobre", about_path, class: "glyphicon glyphicon-user" %>
                    </li>
                    <li>
                        <%= link_to 'Portfolio', works_path, class: "glyphicon glyphicon-tasks" %>
                    </li>
                    <li>
                        <%= link_to "Contato", new_contact_path, class: "glyphicon glyphicon-envelope" %>
                    </li>
                    
                    <% if user_signed_in? %>
                        <li><%= link_to "Perfil", edit_user_registration_path, class: "btn btn-primary btn-sm" %></li>
                        <li><%= link_to "Sair", destroy_user_session_path, class: "btn btn-danger btn-sm", method: :delete %>
                    <% else %>
                        <li><%= link_to "Registrar", new_user_registration_path, class: "btn btn-success btn-sm " %></li>
                        <li><%= link_to "Entrar", new_user_session_path, class: "btn btn-primary btn-sm " %></li>
                        <li><%= link_to "Entrar com Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-primary" %></li>
                 
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_pageheader.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Micoli's Blog</h1>
                        <hr class="small">
                        <span class="subheading">Meu espaço para compartilhar</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/pageheader' %>
<div class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		= render 'layouts/header' 
	%body

		= render 'layouts/navigation'


		= render 'layouts/pageheader'

		.container
			- flash.each do |name, msg|
				= content_tag :div, msg, class: "alert alert-info"
			= yield

		= render 'layouts/footer'